redis:
  host: redis
  port: :6379
  password: password # Должен совпадать с паролем в docker-compose

server:
  http:
    domain: api.gurubot.pro/medcolosma/
    http_address: :8080    # Меняем на 8080, чтобы не драться с Coolify за 80 порт
    https_address: ""      # Оставляем пустым! SSL возьмет на себя Coolify
  grpc:
    domain: api.gurubot.pro/medcolosma/
    address: :50051